/**
 *	@property Version - autogenerated with build script, holds current verison info
 */
// DO NOT EDIT. Updated from version.json
SQR.Version = {"version":"3","build":72,"date":"2015-03-05T02:19:59.655Z"};